// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXPphU2TNGRbJx7SDj3FtRBtFKGO6180',
    appId: '1:646479435316:web:a9f2d963ac7b5fe6575c61',
    messagingSenderId: '646479435316',
    projectId: 'kappfari-9fe8d',
    authDomain: 'kappfari-9fe8d.firebaseapp.com',
    storageBucket: 'kappfari-9fe8d.appspot.com',
    measurementId: 'G-HMZ70FYCND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz5nlFxt4r7VuN3tfElN1luhom-wFv0O4',
    appId: '1:646479435316:android:b5f0f380246c2edf575c61',
    messagingSenderId: '646479435316',
    projectId: 'kappfari-9fe8d',
    storageBucket: 'kappfari-9fe8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNAPZbKn2F1an0Urf6IfD8-3RnADt7bsw',
    appId: '1:646479435316:ios:1d60da883e415c71575c61',
    messagingSenderId: '646479435316',
    projectId: 'kappfari-9fe8d',
    storageBucket: 'kappfari-9fe8d.appspot.com',
    iosBundleId: 'com.example.kappfari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNAPZbKn2F1an0Urf6IfD8-3RnADt7bsw',
    appId: '1:646479435316:ios:1d60da883e415c71575c61',
    messagingSenderId: '646479435316',
    projectId: 'kappfari-9fe8d',
    storageBucket: 'kappfari-9fe8d.appspot.com',
    iosBundleId: 'com.example.kappfari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKXPphU2TNGRbJx7SDj3FtRBtFKGO6180',
    appId: '1:646479435316:web:17559a0af80968b0575c61',
    messagingSenderId: '646479435316',
    projectId: 'kappfari-9fe8d',
    authDomain: 'kappfari-9fe8d.firebaseapp.com',
    storageBucket: 'kappfari-9fe8d.appspot.com',
    measurementId: 'G-HYEE9VJLPB',
  );
}
